/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package imperiumsurvival;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author onorati.nicolo
 */
public class CampoDaGioco extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CampoDaGioco.class.getName());

    /**
     * Creates new form CampoDaGioco
     */
    private Imperatore imperatoreCorrente;
    private GameManager gameManager;

    public CampoDaGioco() {
        initComponents();
        
        // Impostazione dello sfondo (questo va bene nel costruttore)
        ImageIcon s = new ImageIcon(getClass().getResource("sfondo_battaglia.png"));
        Image img = s.getImage().getScaledInstance(1040, 400, Image.SCALE_SMOOTH);
        sfondo.setIcon(new ImageIcon(img));
    }

    // 2. Metodo per inserire i dati (FUORI dal costruttore)
    public void setImperatore(Imperatore scelto) {
        this.imperatoreCorrente = scelto;
        this.gameManager = new GameManager(scelto);
        
        // Carica l'immagine nella Label lbl_pers
        ImageIcon icon = new ImageIcon(getClass().getResource(scelto.getPathImmagine()));
        
        // Ridimensiona l'immagine per la Label del personaggio
        Image img = icon.getImage().getScaledInstance(lbl_pers.getWidth(), lbl_pers.getHeight(), Image.SCALE_SMOOTH);
        lbl_pers.setIcon(new ImageIcon(img));
        lbl_pers.setText("");
        
       
        jLabel7.setText(String.valueOf(scelto.getSalute()));
        jLabel8.setText(String.valueOf(scelto.getDissenso()));
        jLabel6.setText(String.valueOf(scelto.getMalcontento()));
    }
        
             

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_pers = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_eventi = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btn_marcia = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbl_pers.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pers.setText("PERSONAGGIO");
        getContentPane().add(lbl_pers);
        lbl_pers.setBounds(80, 110, 100, 140);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MALCONTENTO:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 340, 100, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SALUTE:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 280, 60, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DISSENSO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 310, 70, 16);

        txtA_eventi.setColumns(20);
        txtA_eventi.setRows(5);
        jScrollPane1.setViewportView(txtA_eventi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(300, 10, 400, 86);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("IMMAGINI EVENTI");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(780, 70, 190, 140);

        btn_marcia.setText("MARCIA");
        btn_marcia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_marciaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_marcia);
        btn_marcia.setBounds(900, 310, 130, 80);

        jButton2.setText("ABILITA' SPECIALE");
        getContentPane().add(jButton2);
        jButton2.setBounds(420, 100, 140, 23);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("0");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 340, 30, 16);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("0");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 280, 30, 16);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("0");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(260, 310, 30, 16);

        sfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imperiumsurvival/sfondo_battaglia.png"))); // NOI18N
        sfondo.setText("jLabel1");
        getContentPane().add(sfondo);
        sfondo.setBounds(-2, 0, 1040, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_marciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_marciaActionPerformed
        
               
        gameManager.cliccaMArcia();
        Evento event = gameManager.getUltimoEvento();
        
        if(event != null){
            txtA_eventi.append("TURNO: " + gameManager.getTurno() + "\n");
            txtA_eventi.append("EVENTO: " + event.getLogTitolo() + "\n");
            txtA_eventi.append("ESIT: " + event.getLogMessaggio() + "\n");
            txtA_eventi.append("---------------------------------\n");
        }
        else{
            txtA_eventi.append("Errore: Nessun evento estratto!\n");
        }
        
        try {
            // Aggiungiamo "/Immagine/" prima del nome del file
            String percorsoImmagine = "/imperiumsurvival/Immagine/" + event.getPahtImmagine().trim();
    
            java.net.URL imgURL = getClass().getResource(percorsoImmagine);
    
            if (imgURL != null) {
                ImageIcon iconEv = new ImageIcon(imgURL);
                Image imgScaled = iconEv.getImage().getScaledInstance(jLabel5.getWidth(), jLabel5.getHeight(), Image.SCALE_SMOOTH);
                jLabel5.setIcon(new ImageIcon(imgScaled));
                jLabel5.setText(""); 
        } else {
            throw new Exception("URL nullo per: " + percorsoImmagine);
        }
        } catch (Exception e) {
            System.err.println("Errore caricamento: " + e.getMessage());
            jLabel5.setIcon(null);
            jLabel5.setText("Immagine non trovata");
        }
        
    }//GEN-LAST:event_btn_marciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CampoDaGioco().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_marcia;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_pers;
    private javax.swing.JLabel sfondo;
    private javax.swing.JTextArea txtA_eventi;
    // End of variables declaration//GEN-END:variables
}
