/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package imperiumsurvival;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author onorati.nicolo
 */
public class ScegliPersonaggio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ScegliPersonaggio.class.getName());

    /**
     * Creates new form ScegliPersonaggio
     */
    public ScegliPersonaggio() {
        
        initComponents();
        this.setSize(1121,542);
        
        btn_car_gc.setOpaque(false);
        btn_car_gc.setContentAreaFilled(false);
        btn_car_gc.setBorderPainted(false);
        
        btn_car_a.setOpaque(false);
        btn_car_a.setContentAreaFilled(false);
        btn_car_a.setBorderPainted(false);
        
        
        btn_car_n.setOpaque(false);
        btn_car_n.setContentAreaFilled(false);
        btn_car_n.setBorderPainted(false);
        
        
        btn_car_ma.setOpaque(false);
        btn_car_ma.setContentAreaFilled(false);
        btn_car_ma.setBorderPainted(false);
        
        
        
        
        
        
        // 1. Carica l'immagine (Assicurati che il nome file sia identico a quello nella cartella)
        ImageIcon immagineImp = new ImageIcon(getClass().getResource("Giulio_Cesare.png"));

        // 2. Ridimensiona (Corretto il typo da immaginImp a immagineImp)
        Image img = immagineImp.getImage(); 
        Image imgRidimensionata = img.getScaledInstance(171,320, Image.SCALE_SMOOTH);
        immagineImp = new ImageIcon(imgRidimensionata);
    
        // 3. AGGIUNGI QUESTA RIGA: applica l'icona al bottone
        jButton4.setIcon(immagineImp);
        
        
        // 1. Carica l'immagine (Assicurati che il nome file sia identico a quello nella cartella)
        ImageIcon immagineImp1 = new ImageIcon(getClass().getResource("Augusto.png"));

        // 2. Ridimensiona (Corretto il typo da immaginImp a immagineImp)
        Image img1 = immagineImp1.getImage(); 
        Image imgRidimensionata1 = img1.getScaledInstance(171,320, Image.SCALE_SMOOTH);
        immagineImp1 = new ImageIcon(imgRidimensionata1);
    
        // 3. AGGIUNGI QUESTA RIGA: applica l'icona al bottone
        jButton3.setIcon(immagineImp1);
        
        
        
        // 1. Carica l'immagine (Assicurati che il nome file sia identico a quello nella cartella)
        ImageIcon immagineImp2 = new ImageIcon(getClass().getResource("Nerone.png"));

        // 2. Ridimensiona (Corretto il typo da immaginImp a immagineImp)
        Image img2 = immagineImp2.getImage(); 
        Image imgRidimensionata2 = img2.getScaledInstance(171,320, Image.SCALE_SMOOTH);
        immagineImp2 = new ImageIcon(imgRidimensionata2);
    
        // 3. AGGIUNGI QUESTA RIGA: applica l'icona al bottone
        jButton2.setIcon(immagineImp2);
        
        
        
        // 1. Carica l'immagine (Assicurati che il nome file sia identico a quello nella cartella)
        ImageIcon immagineImp3 = new ImageIcon(getClass().getResource("Marco_Aurelio.png"));

        // 2. Ridimensiona (Corretto il typo da immaginImp a immagineImp)
        Image img3 = immagineImp3.getImage(); 
        Image imgRidimensionata3 = img3.getScaledInstance(171,320, Image.SCALE_SMOOTH);
        immagineImp3 = new ImageIcon(imgRidimensionata3);
    
        // 3. AGGIUNGI QUESTA RIGA: applica l'icona al bottone
        jButton1.setIcon(immagineImp3);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btn_preambolo = new javax.swing.JButton();
        lbl_titolo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btn_car_gc = new javax.swing.JButton();
        btn_car_a = new javax.swing.JButton();
        btn_car_n = new javax.swing.JButton();
        btn_car_ma = new javax.swing.JButton();
        btn_regolamento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imperiumsurvival/Marco_Aurelio.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(885, 186, 171, 320);

        btn_preambolo.setText("PREAMBOLO");
        btn_preambolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_preamboloActionPerformed(evt);
            }
        });
        getContentPane().add(btn_preambolo);
        btn_preambolo.setBounds(990, 0, 130, 23);

        lbl_titolo.setFont(new java.awt.Font("Trajan Pro", 0, 48)); // NOI18N
        lbl_titolo.setForeground(new java.awt.Color(153, 153, 153));
        lbl_titolo.setText("IMPERIUM SURVIVAL: L'ALBA DEL SANGUE");
        getContentPane().add(lbl_titolo);
        lbl_titolo.setBounds(6, 35, 994, 120);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imperiumsurvival/Nerone.png"))); // NOI18N
        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(616, 186, 171, 320);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imperiumsurvival/Augusto.png"))); // NOI18N
        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(343, 186, 171, 320);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imperiumsurvival/Giulio_Cesare.png"))); // NOI18N
        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(73, 186, 171, 320);

        btn_car_gc.setForeground(new java.awt.Color(102, 255, 255));
        btn_car_gc.setText("caratteristiche");
        btn_car_gc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_car_gcActionPerformed(evt);
            }
        });
        getContentPane().add(btn_car_gc);
        btn_car_gc.setBounds(70, 510, 170, 23);

        btn_car_a.setForeground(new java.awt.Color(102, 255, 255));
        btn_car_a.setText("caratteristiche");
        btn_car_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_car_aActionPerformed(evt);
            }
        });
        getContentPane().add(btn_car_a);
        btn_car_a.setBounds(350, 510, 160, 23);

        btn_car_n.setForeground(new java.awt.Color(102, 255, 255));
        btn_car_n.setText("caratteristiche");
        btn_car_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_car_nActionPerformed(evt);
            }
        });
        getContentPane().add(btn_car_n);
        btn_car_n.setBounds(614, 510, 170, 23);

        btn_car_ma.setForeground(new java.awt.Color(102, 255, 255));
        btn_car_ma.setText("caratteristiche");
        btn_car_ma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_car_maActionPerformed(evt);
            }
        });
        getContentPane().add(btn_car_ma);
        btn_car_ma.setBounds(884, 510, 170, 23);

        btn_regolamento.setText("REGOLAMENTO");
        btn_regolamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regolamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regolamento);
        btn_regolamento.setBounds(990, 30, 130, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imperiumsurvival/fondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1120, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       CampoDaGioco finestraGioco = new CampoDaGioco();
    
        finestraGioco.setImperatore(new Augusto());
    
        finestraGioco.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_preamboloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_preamboloActionPerformed
        JOptionPane.showMessageDialog(null, "IL DESTINO DI ROMA\n\n"
            + "Siamo nel cuore dell'Impero. Le frontiere vacillano sotto la pressione dei barbari,\n"
            + "mentre all'interno delle mura il potere è un veleno che corrompe ogni anima.\n\n"
            + "Il Senato è diviso, le legioni chiedono un leader forte e il popolo muore di fame.\n"
            + "Quattro grandi uomini potrebbero cambiare il corso della storia, ma solo uno\n"
            + "prenderà il comando. La tua scelta segnerà l'eternità.\n\n"
            + "Scegli con saggezza: ogni Imperatore ha punti di forza e oscuri segreti.");
    }//GEN-LAST:event_btn_preamboloActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CampoDaGioco finestraGioco = new CampoDaGioco();
    
        finestraGioco.setImperatore(new GiulioCesare());
    
        finestraGioco.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_car_gcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_car_gcActionPerformed
        String infoCesare = "<html><body style='width: 300px; padding: 5px;'>"
        + "<h1 style='color: #8b0000; margin-bottom: 0;'>GIULIO CESARE</h1>"
        + "<i style='color: #7f8c8d;'>\"Alea Iacta Est - Il dado è tratto.\"</i><br><br>"
        + "<b style='color: #27ae60;'>BONUS PASSIVO: Disciplina Ferrea</b><br>"
        + "• <b style='color: #c0392b;'>-20 Dissenso Militare</b> iniziale.<br>"
        + "Le legioni sono ai tuoi ordini e difficilmente oseranno tradirti all'inizio.<br><br>"
        + "<b style='color: #8b0000;'>ABILITÀ SPECIALE: Azzardo del Rubicone</b><br>"
        + "Azzera istantaneamente il <b style='color: #27ae60;'>Malcontento Popolare</b> grazie al tuo carisma,<br>"
        + "ma il Senato trema: ricevi subito <b style='color: #c0392b;'>+20 Dissenso Militare</b>.<br><br>"
        + "<b>RISCHIO:</b> Attento alle Idi di Marzo! Un eccesso di potere militare <br>"
        + "può portare i complottisti a colpirti nell'ombra."
        + "</body></html>";

        JOptionPane.showMessageDialog(null, infoCesare, "Dettagli Imperatore", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btn_car_gcActionPerformed

    private void btn_car_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_car_aActionPerformed
        String infoAugusto = "<html><body style='width: 300px; padding: 5px;'>"
        + "<h1 style='color: #2980b9; margin-bottom: 0;'>AUGUSTO</h1>"
        + "<i style='color: #7f8c8d;'>\"Ho trovato una città di mattoni, ve la restituisco di marmo.\"</i><br><br>"
        + "<b style='color: #27ae60;'>BONUS PASSIVO:</b><br>"
        + "• <b style='color: #c0392b;'>+30 Salute</b> iniziale (Resistenza superiore).<br><br>"
        + "<b style='color: #2980b9;'>ABILITÀ SPECIALE: Pax Romana</b><br>"
        + "Stabilizza l'Impero rigenerando <b style='color: #27ae60;'>+20 Salute</b> e <br>"
        + "riducendo di <b style='color: #27ae60;'>10 punti</b> sia Malcontento che Dissenso.<br><br>"
        + "<b>CONSIGLIO:</b> Ideale per chi vuole una partita lunga e sicura."
        + "</body></html>";

        JOptionPane.showMessageDialog(null, infoAugusto, "Dettagli Imperatore", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_car_aActionPerformed

    private void btn_car_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_car_nActionPerformed
        String infoNerone = "<html><body style='width: 300px; padding: 5px;'>"
        + "<h1 style='color: #e67e22; margin-bottom: 0;'>NERONE</h1>"
        + "<i style='color: #7f8c8d;'>\"Quale artista muore con me!\"</i><br><br>"
        + "<b style='color: #27ae60;'>BONUS PASSIVO:</b><br>"
        + "• <b style='color: #c0392b;'>-20 Malcontento Popolare</b> (Il popolo ti ama).<br><br>"
        + "<b style='color: #d35400;'>ABILITÀ SPECIALE: Grande Incendio</b><br>"
        + "Elimina ogni minaccia militare (<b style='color: #27ae60;'>Dissenso a 0</b>), <br>"
        + "ma lo stress estremo ti costa <b style='color: #c0392b;'>-30 Salute</b>.<br><br>"
        + "<b>RISCHIO:</b> Attento a non bruciare te stesso insieme a Roma!"
        + "</body></html>";

        JOptionPane.showMessageDialog(null, infoNerone, "Dettagli Imperatore", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btn_car_nActionPerformed

    private void btn_car_maActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_car_maActionPerformed
        String infoMarcoAurelio = "<html><body style='width: 300px; padding: 5px;'>"
        + "<h1 style='color: #8e44ad; margin-bottom: 0;'>MARCO AURELIO</h1>"
        + "<i style='color: #7f8c8d;'>\"La felicità dipende dalla qualità dei tuoi pensieri.\"</i><br><br>"
        + "<b style='color: #27ae60;'>BONUS PASSIVO:</b><br>"
        + "• <b style='color: #c0392b;'>+15 Salute</b> e <b style='color: #c0392b;'>-10 Dissenso</b> iniziale.<br><br>"
        + "<b style='color: #8e44ad;'>ABILITÀ SPECIALE: Meditazioni</b><br>"
        + "Per <b style='color: #2980b9;'>3 turni</b> le tue statistiche sono bloccate e <br>"
        + "i danni degli eventi negativi sono <b style='color: #27ae60;'>dimezzati</b>.<br><br>"
        + "<b>NOTA:</b> Durante la meditazione non ricevi bonus dagli eventi positivi."
        + "</body></html>";

        JOptionPane.showMessageDialog(null, infoMarcoAurelio, "Dettagli Imperatore", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_btn_car_maActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CampoDaGioco finestraGioco = new CampoDaGioco();
    
        finestraGioco.setImperatore(new Nerone());
    
        finestraGioco.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CampoDaGioco finestraGioco = new CampoDaGioco();
    
        finestraGioco.setImperatore(new MarcoAurelio());
    
        finestraGioco.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_regolamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regolamentoActionPerformed
        JOptionPane.showMessageDialog(this,
                "🏛️ BENVENUTO IN IMPERIUM SURVIVAL 🏛️\n\n"
                + "Il tuo obiettivo è sopravvivere il più a lungo possibile sul trono di Roma.\n\n"
                + "📊 STATISTICHE PRINCIPALI:\n"
                + "• SALUTE: Se arriva a 0, muori per malattia o attentato.\n"
                + "• DISSENSO: Rappresenta l'ira dei militari. A 100 verrai deposto dai pretoriani.\n"
                + "• MALCONTENTO: Rappresenta la rabbia del popolo. A 100 scoppierà una rivolta.\n\n"
                + "💰 ECONOMIA E TURNI:\n"
                + "• Ogni volta che clicchi 'MARCIA', guadagni 1 MONETA e affronti un evento.\n"
                + "• PAGA POPOLO (4 monete): Riduce il Malcontento di 15 punti.\n"
                + "• PAGA ESERCITO (4 monete): Riduce il Dissenso di 15 punti.\n\n"
                + "🌟 ABILITÀ SPECIALE:\n"
                + "• Ogni Imperatore ha un potere unico utilizzabile UNA SOLA VOLTA per partita.\n"
                + "• Usala con saggezza nei momenti di crisi!\n\n"
                + "💾 SALVATAGGIO:\n"
                + "• Puoi salvare in CSV (leggibile) o SER (binario) per riprendere la scalata al potere.",
                "Regolamento Imperiale", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_regolamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ScegliPersonaggio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_car_a;
    private javax.swing.JButton btn_car_gc;
    private javax.swing.JButton btn_car_ma;
    private javax.swing.JButton btn_car_n;
    private javax.swing.JButton btn_preambolo;
    private javax.swing.JButton btn_regolamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_titolo;
    // End of variables declaration//GEN-END:variables
}
