/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package imperiumsurvival;

import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author onorati.nicolo
 */
public class ScegliPersonaggio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ScegliPersonaggio.class.getName());

    /**
     * Creates new form ScegliPersonaggio
     */
    public ScegliPersonaggio() {
        
        initComponents();
        
        // 1. Carica l'immagine (Assicurati che il nome file sia identico a quello nella cartella)
        ImageIcon immagineImp = new ImageIcon(getClass().getResource("Giulio_Cesare.png"));

        // 2. Ridimensiona (Corretto il typo da immaginImp a immagineImp)
        Image img = immagineImp.getImage(); 
        Image imgRidimensionata = img.getScaledInstance(171,320, Image.SCALE_SMOOTH);
        immagineImp = new ImageIcon(imgRidimensionata);
    
        // 3. AGGIUNGI QUESTA RIGA: applica l'icona al bottone
        jButton4.setIcon(immagineImp);
        
        
        // 1. Carica l'immagine (Assicurati che il nome file sia identico a quello nella cartella)
        ImageIcon immagineImp1 = new ImageIcon(getClass().getResource("Augusto.png"));

        // 2. Ridimensiona (Corretto il typo da immaginImp a immagineImp)
        Image img1 = immagineImp1.getImage(); 
        Image imgRidimensionata1 = img1.getScaledInstance(171,320, Image.SCALE_SMOOTH);
        immagineImp1 = new ImageIcon(imgRidimensionata1);
    
        // 3. AGGIUNGI QUESTA RIGA: applica l'icona al bottone
        jButton3.setIcon(immagineImp1);
        
        
        
        // 1. Carica l'immagine (Assicurati che il nome file sia identico a quello nella cartella)
        ImageIcon immagineImp2 = new ImageIcon(getClass().getResource("Nerone.png"));

        // 2. Ridimensiona (Corretto il typo da immaginImp a immagineImp)
        Image img2 = immagineImp2.getImage(); 
        Image imgRidimensionata2 = img2.getScaledInstance(171,320, Image.SCALE_SMOOTH);
        immagineImp2 = new ImageIcon(imgRidimensionata2);
    
        // 3. AGGIUNGI QUESTA RIGA: applica l'icona al bottone
        jButton2.setIcon(immagineImp2);
        
        
        
        // 1. Carica l'immagine (Assicurati che il nome file sia identico a quello nella cartella)
        ImageIcon immagineImp3 = new ImageIcon(getClass().getResource("Marco_Aurelio.png"));

        // 2. Ridimensiona (Corretto il typo da immaginImp a immagineImp)
        Image img3 = immagineImp3.getImage(); 
        Image imgRidimensionata3 = img3.getScaledInstance(171,320, Image.SCALE_SMOOTH);
        immagineImp3 = new ImageIcon(imgRidimensionata3);
    
        // 3. AGGIUNGI QUESTA RIGA: applica l'icona al bottone
        jButton1.setIcon(immagineImp3);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btn_istruzioni = new javax.swing.JButton();
        lbl_titolo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imperiumsurvival/Marco_Aurelio.png"))); // NOI18N
        jButton1.setText("jButton1");

        btn_istruzioni.setText("ISTRUZIONI");
        btn_istruzioni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_istruzioniActionPerformed(evt);
            }
        });

        lbl_titolo.setText("IMPERIUM SURVIVAL: L'ALBA DEL SANGUE");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imperiumsurvival/Nerone.png"))); // NOI18N
        jButton2.setText("jButton1");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imperiumsurvival/Augusto.png"))); // NOI18N
        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imperiumsurvival/Giulio_Cesare.png"))); // NOI18N
        jButton4.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(lbl_titolo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_istruzioni)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_istruzioni)
                    .addComponent(lbl_titolo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_istruzioniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_istruzioniActionPerformed
        JOptionPane.showMessageDialog(null, "IL DESTINO DI ROMA\n\n"
            + "Siamo nel cuore dell'Impero. Le frontiere vacillano sotto la pressione dei barbari,\n"
            + "mentre all'interno delle mura il potere è un veleno che corrompe ogni anima.\n\n"
            + "Il Senato è diviso, le legioni chiedono un leader forte e il popolo muore di fame.\n"
            + "Quattro grandi uomini potrebbero cambiare il corso della storia, ma solo uno\n"
            + "prenderà il comando. La tua scelta segnerà l'eternità.\n\n"
            + "Scegli con saggezza: ogni Imperatore ha punti di forza e oscuri segreti.");
    }//GEN-LAST:event_btn_istruzioniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ScegliPersonaggio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_istruzioni;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel lbl_titolo;
    // End of variables declaration//GEN-END:variables
}
