/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package imperiumsurvival;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author onorati.nicolo
 */
public class SchermataIniziale extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SchermataIniziale.class.getName());

    /**
     * Creates new form SchermataIniziale
     */
    public SchermataIniziale() {
        initComponents();
        this.setSize(1540,709);
        
        // 1. Carica l'immagine (Assicurati che il nome file sia identico a quello nella cartella)
        ImageIcon iniziale = new ImageIcon(getClass().getResource("schermata_iniziale.png"));

        // 2. Ridimensiona (Corretto il typo da immaginImp a immagineImp)
        Image img = iniziale.getImage(); 
        Image imgRidimensionata = img.getScaledInstance(1160,650, Image.SCALE_SMOOTH);
        iniziale = new ImageIcon(imgRidimensionata);
    
        // 3. AGGIUNGI QUESTA RIGA: applica l'icona al bottone
        jLabel1.setIcon(iniziale);
        
        
        
        
        
        btn_caricaPartita.setOpaque(false);
        btn_caricaPartita.setContentAreaFilled(false);
        btn_caricaPartita.setBorderPainted(false);
        
        btn_creaPartita.setOpaque(false);
        btn_creaPartita.setContentAreaFilled(false);
        btn_creaPartita.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_caricaPartita = new javax.swing.JButton();
        btn_creaPartita = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_caricaPartita.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        btn_caricaPartita.setText("CARICA PARTITA");
        btn_caricaPartita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_caricaPartitaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_caricaPartita);
        btn_caricaPartita.setBounds(440, 380, 260, 70);

        btn_creaPartita.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        btn_creaPartita.setText("NUOVA PARTITA");
        btn_creaPartita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_creaPartitaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_creaPartita);
        btn_creaPartita.setBounds(440, 290, 260, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imperiumsurvival/schermata_iniziale.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(3, -4, 1540, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_caricaPartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_caricaPartitaActionPerformed
       FileManager fm = new FileManager();
       Imperatore caricato = fm.caricaPartitaCSV("salvataggio_imperium");
       
       if(caricato != null){
           this.dispose();
           CampoDaGioco cg = new CampoDaGioco();
           cg.setImperatore(caricato);
           cg.setVisible(true);
           
           JOptionPane.showMessageDialog(cg, "Bentornato, imperatore! Partita caricata.");
       }
       else{
           JOptionPane.showMessageDialog(this, "Nessun salvataggio trovato o file corrotto!", "Errore", javax.swing.JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btn_caricaPartitaActionPerformed

    private void btn_creaPartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_creaPartitaActionPerformed
         this.dispose();
        
        ScegliPersonaggio sp = new ScegliPersonaggio();
        sp.setVisible(true);
    }//GEN-LAST:event_btn_creaPartitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SchermataIniziale().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_caricaPartita;
    private javax.swing.JButton btn_creaPartita;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
